### ISSUE TITLE
[Feature Request] Add AirMessage to F-Droid or the Aurora Store (for custom ROM users)

### ISSUE THREAD

**Issue by CSab6482** [airmessage/airmessage-android#14]

**Comment by nep2ner** [comment]
It's already accessible from the Aurora Store (although with 2 google trackers). Seeing this on F-Droid would be great!

**Comment by tagavari** [comment]
AirMessage relies on closed-source Google libraries and services for some of its features, here's what I can remember:

- **AirMessage Cloud (push notifications + Google sign-in)**
  - I assume that any user of F-Droid probably isn't interested in AirMessage Cloud, so that one's not really an issue.
- **Firebase Analytics + Crashlytics**
  - I'd be fine with disabling Analytics and Crashlytics for F-Droid builds.
- **Security provider updates**
  - While this is nice to have, in practice I haven't seen it used much, and it's only really relevant for devices that don't receive system updates anymore.
- **ML Kit (smart reply)**
  - For devices running Android 10 or older, AirMessage uses Google's ML Kit for reply suggestions at the bottom of the conversations list and in notifications. On Android 11+, AirMessage uses [TextClassifier](https://developer.android.com/reference/android/view/textclassifier/TextClassifier), which is built into the operating system.
  - The ML Kit implementation would have to be disabled for F-Droid builds, and users running a custom ROM may not have access to TextClassifier. From what I've seen, some users like this feature while others keep it turned off, so this would be a tradeoff for some.
- **Google Maps (iMessage location attachments)**
  - This one really comes down to how each user uses iMessage. This would probably have to be one of the tradeoffs of running the F-Droid version. It might be possible to replace Google Maps with OpenStreetMap, though I can't see this being worth it unless there's a large enough number of users on the F-Droid version.

If there's enough interest in getting AirMessage on F-Droid, I'd be happy to work towards that!

**Comment by CSab6482** [comment]
I made a [reddit post](https://www.reddit.com/r/AirMessage/comments/o30jnu/) to see how interested or not interested people were in this feature. For those of you not on r/AirMessage, [here](https://www.strawpoll.me/45411630) is the poll so that you can vote too!

**Comment by nep2ner** [comment]
As you mentioned with AirMessage Cloud, I think most custom ROM users are not interested in smart reply. OSM integration would be phenomenal, though an F-Driod build sans maps support is still worth it. Listing on F-Droid has the potential to reach some new users too.

**Comment by CSab6482** [comment]
Similarly to [my comment on issue 11](https://github.com/airmessage/airmessage-android/issues/11#issuecomment-881999414), I have now posted the results of the vote since it has been a month since it was posted.
![image](https://user-images.githubusercontent.com/53708281/126056489-3032a332-2cdc-4048-852b-850b28858488.png)
10 of the 14 votes were in favor of adding the feature, and the yes votes were evenly split between "I would use this feature all the time." and "I wouldn't use this feature all that much, but it sounds like a good improvement."
There were 3 no votes who felt like the request should not be worked on because the app should focus on other features or fixes, and 1 no vote who would neither notice or use AirMessage on F-Droid.

**Comment by CSab6482** [comment]
In [this reddit post](https://redd.it/oxt0gs/), u/friskfrugt requested a self hosted version of AirMessage Cloud, or one that utilized [Supabase](https://supabase.io/) instead of Firebase. Is this applicable to the information in this ticket? Also, would [microG](https://github.com/microg) be helpful in any way?

**Comment by tagavari** [comment]
Since Supabase doesn't have an equivalent for Firebase Cloud Messaging, it unfortunately cannot replace Firebase.

However, if the main reason for wanting to self-host AirMessage Cloud is the web app, I am still working on porting the client to Windows to allow direct connections.

**Comment by jonaharagon** [comment]
I will say, I am an F-Droid user that would be interested in using AirMessage Cloud. 

microG would provide push notifications via GCM, but for some reason whatever method AirMessage is using to sign-in with Google doesn't seem to work with microG's native Google accounts. I'm just getting a "Sign-in error" popup.

**Comment by tagavari** [comment]
Alright, I've worked a bit on this and the `foss` branch introduces a build flavor that produces a fully open-source version of the app. Everything I mentioned in my original comment is removed, so this flavor will only support direct connections.

I'll have to look more into getting the app onto F-Droid, I may do that later this week.

**Comment by mariobrostech** [comment]
Awesome, thank you so much for your work on this! Hoping for a smooth review process 🤞

**Comment by wyatta4** [comment]
Has there been any progress on this front? Super interested!

**Comment by nep2ner** [comment]
@tagavari Is this still something that is on the table?

**Comment by mariobrostech** [comment]
This is great news, glad to hear you're still committed to an F-Droid release. I'm definitely looking forward to it!

**Comment by tagavari** [comment]
F-Droid merge request has been created here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11493

**Comment by tagavari** [comment]
MR was accepted!

**Comment by tagavari** [comment]
AirMessage is available to download from F-Droid here: https://f-droid.org/packages/me.tagavari.airmessage/

**Comment by nep2ner** [comment]
@tagavari You are amazing! Thanks for your work!
