### ISSUE TITLE
[Feature Request] Allow users to skip the Mac/Google sign in and just use AirMessage as an SMS/MMS app

### ISSUE THREAD

**Issue by CSab6482** [airmessage/airmessage-android#9]
I know this use case is very particular and most people probably don't fall into this group, but if someone wants to use AirMessage as their SMS/MMS app and they have no interest in iMessage, I feel like they should have the option to still access that functionality.

**Comment by tagavari** [comment]
AirMessage is primarily designed to be an iMessage client, and as such a lot of the app is designed around this core functionality.

While it would be possible to allow users to use AirMessage exclusively as an SMS / MMS app, there are dedicated apps made by large companies and third-party developers who are able to structure their app around text messaging and offer a more integrated and feature-rich user experience.

My focus with AirMessage is not to do too much more than iMessage, but to do iMessage really well. I appreciate the feature request, though I'd rather keep AirMessage as an iMessage-focused app, rather than spending more time and effort to tailor the app for both iMessage and regular SMS / MMS users.

**Comment by mariobrostech** [comment]
Hi @tagavari, I respect your decision to make AirMessage an iMessage-focused app. However, since you initially wrote your reply a little over a year ago, a lot has changed in the landscape of Android SMS messengers, particularly in regards to the open-source options that are available.

Pulse SMS, an app that once offered a GitHub repository with its source code, was acquired by Maple Media and had its repository taken offline. Signal, a popular messaging app in the privacy community, is removing the fallback SMS/MMS functionality that made it most useful as an all-in-one messaging app.

The only remaining standalone SMS clients for Android are QKSMS, which, while being a great app, hasn't received an update in multiple years and appears to be abandoned and Simple SMS Messenger, which is very bare-bones, even compared to what AirMessage currently offers for SMS functionality.

That being said, I've tried using AirMessage exclusively as an SMS client, and it went surprisingly well. There's a little-known feature in which you can tap and hold on the manual setup button to skip the setup process altogether. Unfortunately, this appears to have been dropped during the move to Jetpack Compose with AirMessage v4, and I hope you can reconsider this decision. Moving over to AirMessage was a seamless experience; my messages imported smoothly, I retained the rainbow chats feature which I adore from QKSMS, and everything "just works."

I understand that you want AirMessage to be iMessage-focused first and foremost, but it could also be an awesome standalone SMS app. Even if you just took what's in the app right now and remove the background process, server options/notifications, and allow an easy option to use AirMessage as solely an SMS/MMS client, you'd make many users (including myself!) very happy. Particularly with Signal dropping SMS support, I feel like there's a pretty healthy market for a good privacy-focused SMS app, and AirMessage could fill in that gap nicely.

I am more than happy to beta test if you're willing to go forward with this request. Thank you in advance for reading this and for developing AirMessage!

**Comment by tagavari** [comment]
@mariobrostech Thank you for your message, I'm glad that you believe AirMessage is a good enough alternative as an open source SMS app!

I was also disappointed when I heard Signal was dropping SMS support, and I understand the need for a well-supported open source SMS messaging app. However, I'm still concerned that putting time into making AirMessage a good SMS app would take away too much from AirMessage's iMessage development.

I've also learned that maintaining an SMS app is _hard_. Android's messaging API is all over the place and poorly documented. While I could spend the time to figure it out, it unfortunately makes it that much harder to justify maintaining an SMS-dedicated app.

That being said, I'm not at all against making AirMessage more SMS-friendly. iMessage is deeply ingrained into the app's code, though if you or someone else wants to fork AirMessage and turn it into a standalone SMS app, I'd be more than happy to provide support.

_By the way, that trick you found to bypass the setup process was only implemented to get past Google review. If you select **Use manual configuration** and then enter `skip!` into the server address field, you can still bypass setup :)_
